[package]
edition = "2021"
name = "view-ash"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.36.0+1.3.206"
ash-window = "0.9.1"
env_logger = "0.9.0"
glam = "0.20.2"
image = "0.24.1"
log = "0.4.14"
tobj = "3.2.1"
winit = "0.26.1"
